Vagrant.configure("2") do |config|
	config.vm.box = "debian/trixie64"
	config.vm.boot_timeout = 600
	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.define "osivkovS" do |server|
		server.vm.hostname = "osivkovS"
	
		server.vm.provider :libvirt do |libvirt|
			libvirt.cpus = 3
			libvirt.memory = 3072
		end

		server.vm.network "private_network",
			ip: "192.168.56.110",
			libvirt__network_name: "iotnet"
			
		server.vm.provision "shell", path: "scripts/server.sh"
	end
end
